export const GAME_SEASON_TAGS = [
    { value: "PK24", label: "PK24 漢焰長明" },
    { value: "PK23", label: "PK23 英雄命世" },
    { value: "PK22", label: "PK22 長安之亂" },
    { value: "PK21", label: "PK21 霸王討逆" },
    { value: "PK20", label: "PK20 定軍山之戰" },
    { value: "PK19", label: "PK19 兗州之戰" },
    { value: "PK18", label: "PK18 亂世烽煙" },
    { value: "PK17", label: "PK17 奇門八陣" },
    { value: "PK16", label: "PK16 潼關之戰" },
    { value: "PK15", label: "PK15 陳倉之戰" },
    { value: "PK14", label: "PK14 天師舉義" },
    { value: "PK13", label: "PK13 雲起龍襄" },
    { value: "PK12", label: "PK12 襄樊之戰" },
    { value: "PK11", label: "PK11 兵戰四時" },
    { value: "PK10", label: "PK10 英雄集結" },
    { value: "PK9", label: "PK9 王師秉節" },
    { value: "PK8", label: "PK8 官渡之戰" },
    { value: "PK7", label: "PK7 北定中原" },
    { value: "PK6", label: "PK6 興師伐亂" },
    { value: "PK5", label: "PK5 軍爭地利" },
    { value: "PK4", label: "PK4 赤壁之戰" },
    { value: "PK3", label: "PK3 英雄露穎" },
    { value: "PK2", label: "PK2 天下爭鋒" },
    { value: "PK1", label: "PK1 群雄割據" },
] as const;
